os: linux
dist: bionic
sudo: false

services:
  - docker

language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2

env:
  global:
    - secure: "N9GRRMn02u+CEZwm73uQKL/rdWvncm7Roo4vXDWNFlHmtvNXMOK+NkLumQlDhV+hCyCcpdnPFZowRnOm4624yyyCpJ+RRyabXaI6vQI0WZU+jX31hyKGstbTFn5lXHYZReTRX4N0kWfMVjZ2vyC+FVnveGl8xbAaQvtXBAdiGzfQ0/VSx/9lRUZi8ch4usy9mtk4bAMRRoA0QK5JvEUk1+Db4CNcFxZfThlBSv1UugcJgLb38Rj9pFTnpvB5rF8l7FdksMEhPhLreiWDEPrC68qYFIBHTUJSzkin7ScMyBqGxx3udvid8YrUqzaEWRsc58/s9Mbdcb62nWAQNwc7l5xjR4aBxWLomlPf2DriVDistW0pHTID86Fd1pw/PY96E4aE59tiTyTwVtOOJjFKbKaia+v6AGlUbun7iajmeNtiybJfzXRWt8EYlA202HbG7ubcNSOJxguLrgfkYCdYs0exB4howEHPuBGjmarv88KGxq/jhLs28TY0Ud9K1nSYMJBv5oFHt2zCFEU9naP0U2uiwA2JVgEWM/CkIOpDizF0YmLbUbk0bJtepoPbTtTCYfQxbAKVlGYj36WN7+IZhBB235JO+8XWgLJA2PZyOXymby8OIaXqQdDIzbbXDo450tL+pyH8rol/OWs6aWRCiDBWieh9Jt/NUkDoFy7MNqI="
    - secure: "sClQBOOZrBFm5mfLRtGHqxeTZJsrOh4bzhSFX3ysEA4G+RI3yWB9veVsDflq0xl6N/NWqTokeSbwUKh03hBq9BCHRJT4sdD1CIR13X30h0x6VETw73DxthREBhEbf19xD1SKJB5fBnOtIYSlFAgr+X++h9gmXieCkdGpnlxlTcywKGzgumeibA7oD2lF/t+tH//j+KcHNZ8T/Y8uGNNZe0ydijcCkloltJIg1iBL2aih9D5XzlSyhzoTeTy/L39P/adb8Irk68cbqTFYHbj1ZsTFZiUsJIMP7qR6FNh3wARemIftRhuq7xOL2DZ0AebdNtXVp290PtC2Y7wZ85UvdwZXu4kxIHuhz/Zxl3Z2d9FfomF10y8ej4Kcd8A2p0WOB2LQpsHgBntrFKvlwsTfrZvtXmoQ8LtfD653H+F1rVcyeao1v1A7ej6t909xG/h46Ug8mXFyX0qspn4OXvQvbZ2HPCMIKVjrEFd8sDD1g8wqEH9oRM/gky6zCB+kKddmIeVO0SLKHwdmJMPWEkK/zUN7pB2LWN5RRqr1uk2aYLFWNpgcI8H12jwmdSw+EfdMcyY8TEk7QBTfwknVhWxvhEtHgLlD3GRlTIbNbr+8Pyup+IpeQwV190dq9Epz6inbZKqZAUdv4Go1GNZCnG8T7XwdhN5Doo6ka70xju1wxZk="

before_deploy:
  - docker build -t mjam/se-rest:latest .

deploy:
  on:
    branch: master
  provider: script
  script: bash docker_push.sh
