version: "3.6"

services:

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data

  flyway:
    depends_on:
      - postgres
    image: flyway/flyway:6-alpine
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/test
      FLYWAY_USER: test
      FLYWAY_PASSWORD: test
    volumes:
      - ./sql:/flyway/sql
    command: migrate
    restart: on-failure

  se-rest:
    depends_on:
      - postgres
    image: openjdk:11-jdk-slim
    ports:
      - 8080:8080
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: test
      QUARKUS_OIDC_ENABLED: "false"
    volumes:
      - ./.mvn:/app/.mvn
      - ./mvnw:/app/mvnw
      - ./pom.xml:/app/pom.xml
      - ./src:/app/src
    working_dir: /app
    command: ./mvnw quarkus:dev

volumes:
  postgres:
